# Generated by Django 4.2.16 on 2024-11-07 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fresh_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favourite',
        ),
        migrations.AlterField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
