# Generated by Django 4.2.16 on 2024-11-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh_app', '0002_rename_favorite_favourite_alter_event_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
